import { ItemDetailsModel } from "./models/index.js";

const ITEM_LIST: ItemDetailsModel[] = [
  {
    key: 1,
    name: `Cleanrot knights sword`,
    img: "/swords/cleanrot-knights-sword.png",
    img2: "/swords/blacksmiths-will.png",
    price: 205,
    description: "Esta es una espada maravillosa",
    origin: "Elden Ring",
  },
  {
    key: 2,
    name: `Blacksmith’s Will`,
    img: "/swords/blacksmiths-will.png",
    img2: "/swords/cleanrot-knights-sword.png",
    price: 305,
    description: "Esta es una espada maravillosa",
    origin: "Dungeons & Dragons",
  },
  {
    key: 3,
    name: `Wing of Aester`,
    img: "/swords/wing-of-aester.png",
    img2: "/swords/anduril.png",
    price: 405,
    description: "Esta es una espada maravillosa",
    origin: "Elden Ring",
  },
  {
    key: 4,
    name: `Anduril`,
    img: "/swords/anduril.png",
    img2: "/swords/wing-of-aester.png",
    price: 95,
    description: "Esta es una espada maravillosa",
    origin: "The Lord of the Rings",
  },
  {
    key: 5,
    name: `Moonlight Greatsword`,
    img: "/swords/moonlight-greatsword.png",
    img2: "/swords/cleanrot-knights-sword.png",
    price: 105,
    description: "Esta es una espada maravillosa",
    origin: "Elden Ring",
  },
  {
    key: 6,
    name: `Cleanrot knights sword 2`,
    img: "/swords/cleanrot-knights-sword.png",
    img2: "/swords/blacksmiths-will.png",
    price: 205,
    description: "Esta es una espada maravillosa",
    origin: "Elden Ring",
  },
  {
    key: 7,
    name: `Blacksmith’s Will 2`,
    img: "/swords/blacksmiths-will.png",
    img2: "/swords/cleanrot-knights-sword.png",
    price: 305,
    description: "Esta es una espada maravillosa",
    origin: "Dungeons & Dragons",
  },
  {
    key: 8,
    name: `Wing of Aester 2`,
    img: "/swords/wing-of-aester.png",
    img2: "/swords/anduril.png",
    price: 405,
    description: "Esta es una espada maravillosa",
    origin: "Elden Ring",
  },
  {
    key: 9,
    name: `Anduril 2`,
    img: "/swords/anduril.png",
    img2: "/swords/wing-of-aester.png",
    price: 95,
    description: "Esta es una espada maravillosa",
    origin: "The Lord of the Rings",
  },
  {
    key: 10,
    name: `Moonlight Greatsword 2`,
    img: "/swords/moonlight-greatsword.png",
    img2: "/swords/cleanrot-knights-sword.png",
    price: 105,
    description: "Esta es una espada maravillosa",
    origin: "Elden Ring",
  },
];

export default ITEM_LIST;
