import { ItemDetailsModel } from "./models/index.js";

const ITEM_LIST: ItemDetailsModel[] = [
  {
    key: 1,
    name: "Espada del caballero imputrescible",
    nameEn: "Cleanrot knights sword",
    img: "/swords/cleanrot-knights-sword.png",
    img2: "/swords/blacksmiths-will.png",
    price: 205,
    description: "Esta es una espada maravillosa",
    descriptionEn: "This is an awesome sword",
    origin: "Elden Ring",
  },
  {
    key: 2,
    name: "La voluntad del herrero",
    nameEn: `Blacksmith’s will`,
    img: "/swords/blacksmiths-will.png",
    img2: "/swords/cleanrot-knights-sword.png",
    price: 305,
    description: "Esta es una espada maravillosa",
    descriptionEn:
      "a magic silver longsword used by Greghor Kardh, a forge cleric",
    origin: "Dungeons & Dragons",
  },
  {
    key: 3,
    name: "Ala de Aestel",
    nameEn: "Wing of Aestel",
    img: "/swords/wing-of-aester.png",
    img2: "/swords/anduril.png",
    price: 405,
    description: "Esta es una espada maravillosa",
    descriptionEn: "This is an awesome sword",
    origin: "Elden Ring",
  },
  {
    key: 4,
    name: "Anduril",
    nameEn: "Anduril",
    img: "/swords/anduril.png",
    img2: "/swords/wing-of-aester.png",
    price: 95,
    description: "Esta es una espada maravillosa",
    descriptionEn: "This is an awesome sword",
    origin: "The Lord of the Rings",
  },
  {
    key: 5,
    name: "Espadón de la luna negra",
    nameEn: "Darkmoon greatsword",
    img: "/swords/moonlight-greatsword.png",
    img2: "/swords/cleanrot-knights-sword.png",
    price: 105,
    description: "Esta es una espada maravillosa",
    descriptionEn: "This is an awesome sword",
    origin: "Elden Ring",
  },
  {
    key: 6,
    name: "Espada del caballero imputrescible 2",
    nameEn: "Cleanrot knights sword 2",
    img: "/swords/cleanrot-knights-sword.png",
    img2: "/swords/blacksmiths-will.png",
    price: 205,
    description: "Esta es una espada maravillosa",
    descriptionEn: "This is an awesome sword",
    origin: "Elden Ring",
  },
  {
    key: 7,
    name: "La voluntad del herrero 2",
    nameEn: `Blacksmith’s will 2`,
    img: "/swords/blacksmiths-will.png",
    img2: "/swords/cleanrot-knights-sword.png",
    price: 305,
    description: "Esta es una espada maravillosa",
    descriptionEn: "This is an awesome sword",
    origin: "Dungeons & Dragons",
  },
  {
    key: 8,
    name: "Ala de Aestel 2",
    nameEn: "Wing of Aestel 2",
    img: "/swords/wing-of-aester.png",
    img2: "/swords/anduril.png",
    price: 405,
    description: "Esta es una espada maravillosa",
    descriptionEn: "This is an awesome sword",
    origin: "Elden Ring",
  },
  {
    key: 9,
    name: "Anduril 2",
    nameEn: "Anduril 2",
    img: "/swords/anduril.png",
    img2: "/swords/wing-of-aester.png",
    price: 95,
    description: "Esta es una espada maravillosa",
    descriptionEn: "This is an awesome sword",
    origin: "The Lord of the Rings",
  },
  {
    key: 10,
    name: "Espadón de la luna negra 2",
    nameEn: "Darkmoon greatsword 2",
    img: "/swords/moonlight-greatsword.png",
    img2: "/swords/cleanrot-knights-sword.png",
    price: 105,
    description: "Esta es una espada maravillosa",
    descriptionEn: "This is an awesome sword",
    origin: "Elden Ring",
  },
];

export default ITEM_LIST;
